version: '3.2'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    container_name: login-and-board-dev
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-dev
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - $HOME/.gitconfig:/root/.gitconfig
      - .:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: login-and-board
      POSTGRES_USER: login-and-board-dev
      POSTGRES_PASSWORD: login-and-board-dev
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.1-alpine
    command: redis-server --port 6379
    restart: always
    ports:
      - 6379:6379
